#!/bin/sh

set -e

umask 077

basedir=~/.Eryllium
dbfile="$basedir/DB_CONFIG"
cfgfile="$basedir/Eryllium.conf"

[ -e "$basedir" ] || mkdir "$basedir"

# Eryllium does not clean up DB log files by default
[ -e "$dbfile" ] || echo 'set_flags DB_LOG_AUTOREMOVE' > "$dbfile"

exec /usr/lib/Eryllium/Eryllium-qt "$@"
